package POJOS;
// Generated 11/11/2019 09:43:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reservacion generated by hbm2java
 */
public class Reservacion  implements java.io.Serializable {


     private Integer idReservacion;
     private Tarjetas tarjetas;
     private Usuario usuario;
     private Date checkIn;
     private Date checkOut;
     private Set habitacions = new HashSet(0);

    public Reservacion() {
    }

	
    public Reservacion(Tarjetas tarjetas, Usuario usuario, Date checkIn, Date checkOut) {
        this.tarjetas = tarjetas;
        this.usuario = usuario;
        this.checkIn = checkIn;
        this.checkOut = checkOut;
    }
    public Reservacion(Tarjetas tarjetas, Usuario usuario, Date checkIn, Date checkOut, Set habitacions) {
       this.tarjetas = tarjetas;
       this.usuario = usuario;
       this.checkIn = checkIn;
       this.checkOut = checkOut;
       this.habitacions = habitacions;
    }
   
    public Integer getIdReservacion() {
        return this.idReservacion;
    }
    
    public void setIdReservacion(Integer idReservacion) {
        this.idReservacion = idReservacion;
    }
    public Tarjetas getTarjetas() {
        return this.tarjetas;
    }
    
    public void setTarjetas(Tarjetas tarjetas) {
        this.tarjetas = tarjetas;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getCheckIn() {
        return this.checkIn;
    }
    
    public void setCheckIn(Date checkIn) {
        this.checkIn = checkIn;
    }
    public Date getCheckOut() {
        return this.checkOut;
    }
    
    public void setCheckOut(Date checkOut) {
        this.checkOut = checkOut;
    }
    public Set getHabitacions() {
        return this.habitacions;
    }
    
    public void setHabitacions(Set habitacions) {
        this.habitacions = habitacions;
    }




}


