package POJOS;
// Generated 11/11/2019 09:43:59 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tarjetas generated by hbm2java
 */
public class Tarjetas  implements java.io.Serializable {


     private Integer idTarjetas;
     private Usuario usuario;
     private String numero;
     private Set reservacions = new HashSet(0);

    public Tarjetas() {
    }

	
    public Tarjetas(Usuario usuario, String numero) {
        this.usuario = usuario;
        this.numero = numero;
    }
    public Tarjetas(Usuario usuario, String numero, Set reservacions) {
       this.usuario = usuario;
       this.numero = numero;
       this.reservacions = reservacions;
    }
   
    public Integer getIdTarjetas() {
        return this.idTarjetas;
    }
    
    public void setIdTarjetas(Integer idTarjetas) {
        this.idTarjetas = idTarjetas;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public Set getReservacions() {
        return this.reservacions;
    }
    
    public void setReservacions(Set reservacions) {
        this.reservacions = reservacions;
    }




}


