insert into Tipo_Habitacion (Tipo_Habitacioncol) VALUES ('Doble');
insert into Tipo_Habitacion (Tipo_Habitacioncol) VALUES ('Simple');
insert into Direccion (pais, region) VALUES ('Liberia','Tarbes');
insert into Direccion (pais, region) VALUES ('Estonia', 'Laives/Leifers');
insert into Direccion (pais, region) VALUES ('Chad', 'Falun');
insert into Direccion (pais, region) VALUES ('American Samoa', 'Blind River');
insert into Direccion (pais, region) VALUES ('Angola', 'Nanton');
insert into Direccion (pais, region) VALUES ('Costa Rica', 'San Jose');
insert into Direccion (pais, region) VALUES ('Dominican Republic', 'Mataró');
insert into Direccion (pais, region) VALUES ('United Kingdom', 'Treppo Carnico');
insert into Direccion (pais, region) VALUES ('Gabon', 'Caledon');
insert into Direccion (pais, region) VALUES ('Iraq', 'Rouvreux');
insert into Direccion (pais, region) VALUES ('Congo', 'Villa Alemana');
insert into Direccion (pais, region) VALUES ('Uruguay', 'Maringá');
insert into Direccion (pais, region) VALUES ('Benin', 'Etterbeek');
insert into Direccion (pais, region) VALUES ('San Marino', 'Wels');
insert into Direccion (pais, region) VALUES ('Papua New Guinea','Saint-Denis');
insert into Hotel (Direccion_idDireccion, Nombre) VALUES (1,'Hotel Realeza');
insert into Hotel (Direccion_idDireccion, Nombre) VALUES (2, 'Hotel Parissi');
insert into Hotel (Direccion_idDireccion, Nombre) VALUES (3, 'Oz Resort');
insert into Hotel (Direccion_idDireccion, Nombre) VALUES (4, 'Shanti Hotel');
insert into Hotel (Direccion_idDireccion, Nombre) VALUES (5, 'Hotel Kristal');
insert into Hotel (Direccion_idDireccion, Nombre) VALUES (6, 'Linus hotel');
insert into Hotel (Direccion_idDireccion, Nombre) VALUES (7, 'Hotel Bellota');
insert into Hotel (Direccion_idDireccion, Nombre) VALUES (8, 'Hotel Poseidon');
insert into Hotel (Direccion_idDireccion, Nombre) VALUES (9, 'Hotel La Marina');
insert into Hotel (Direccion_idDireccion, Nombre) VALUES (10, 'The Castle Resort');
insert into Hotel (Direccion_idDireccion, Nombre) VALUES (11, 'Hotel Los Pinos');
insert into Hotel (Direccion_idDireccion, Nombre) VALUES (12, 'Candel Resort');
insert into Hotel (Direccion_idDireccion, Nombre) VALUES (13, 'Hotel El bosque');
insert into Hotel (Direccion_idDireccion, Nombre) VALUES (14, 'Hotel Mulan');
insert into Habitacion(Hotel_idHotel, Disponibilidad, Tipo_Habitacion_idTipo_Habitacion) VALUES (1, 'Disponible', 2);
insert into Habitacion(Hotel_idHotel, Disponibilidad, Tipo_Habitacion_idTipo_Habitacion) VALUES (2, 'Disponible', 2);
insert into Habitacion(Hotel_idHotel, Disponibilidad, Tipo_Habitacion_idTipo_Habitacion) VALUES (3, 'Disponible', 1);
insert into Habitacion(Hotel_idHotel, Disponibilidad, Tipo_Habitacion_idTipo_Habitacion) VALUES (4, 'Disponible', 2);
insert into Habitacion(Hotel_idHotel, Disponibilidad, Tipo_Habitacion_idTipo_Habitacion) VALUES (5, 'Disponible', 1);
insert into Habitacion(Hotel_idHotel, Disponibilidad, Tipo_Habitacion_idTipo_Habitacion) VALUES (11, 'Disponible', 2);
insert into Habitacion(Hotel_idHotel, Disponibilidad, Tipo_Habitacion_idTipo_Habitacion) VALUES (12, 'Disponible', 1);
insert into Habitacion(Hotel_idHotel, Disponibilidad, Tipo_Habitacion_idTipo_Habitacion) VALUES (13, 'Disponible', 2);
insert into Habitacion(Hotel_idHotel, Disponibilidad, Tipo_Habitacion_idTipo_Habitacion) VALUES (14, 'Disponible', 1);
insert into Usuario (Nombre, Apellido, FechaNacimiento, Correo, Telefono) VALUES ('Daniela', 'Paniagua', '1998-12-07', 'dani@mail.com', '22552255');
insert into Tarjetas (Usuario_idUsuario, Numero) values (1, '1234567891234');
insert into Reservacion (Usuario_idUsuario, Tarjetas_idTarjetas, CheckIn, CheckOut) VALUES (1,1, '2019-10-01','2019-10-05');
insert into Habitacion_has_Reservacion VALUES(12,1);


